sudo: required

services:
  - docker

script:
  - docker build -t nexus .
  - docker run --name nexus -d nexus
  - travis_wait 10 sleep 600
  - docker exec nexus /bin/sh -c "apk add --no-cache curl && curl -f localhost:8081"
